#region GUI Consts
INIT_WINDOW_SIZE = '700x700'
FRM_BG_COLOR_GREEN = '#16c784'
FRM_BG_COLOR_DARK_GREY = '#333333'
FRM_FG_COLOR_WHITE = '#FFFFFF'

FONT_TITLE = ('Verdana', 24)
FONT_SUBTITLE = ('Verdana', 18)
FONT_BODY = ('Verdana', 14)

#endregion
REST_API_URL_BASE = 'https://jsonplaceholder.typicode.com'


#region DB Consts
SQL_CONNECTION_STRING = 'sqlite:///db_data/py_crypto_app.db'

ENTITY_NAME_LENGHT = 250
ENTITY_DESCRIPTION_LENGHT = 750

ENTITY_EMAIL_LENGHT = 250
ENTITY_PHONE_LENGHT = 50
ENTITY_WEBSITE_LENGHT = 500


# ADDRESS
ADDRESS_STREET_LENGHT = 500
ADDRESS_ZIPCODE_LENGHT = 50


# DECIMALS
ENTITY_PRECISION = 8
ENTITY_SCALE = 6

#endregion